import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "../../styles/globals.scss";
import { NextIntlClientProvider, useMessages } from "next-intl";
import getRequestConfig from "../../i18n";
import { Providers } from "@/context";

const space_grotesk = Space_Grotesk({ subsets: ["latin"] });

export function generateStaticParams() {
  return [{ locale: "es" }, { locale: "ca" }, { locale: "en" }];
}

export const metadata: Metadata = {
  title: "Reviu",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const { messages } = await getRequestConfig({ locale });

  return (
    <html lang={locale} className={space_grotesk.className}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
