export const Idioms = [
  { label: "Català", code: "ca" },
  { label: "Español", code: "es" },
  { label: "English", code: "en" },
];

export enum Countries {
  spain = "España",
  france = "Francia",
  germany = "Alemania",
  italy = "Italia",
  portugal = "Portugal",
  unitedKingdom = "Reino Unido",
  unitedStates = "Estados Unidos",
  argentina = "Argentina",
  brazil = "Brasil",
  chile = "Chile",
  colombia = "Colombia",
}

export const Genders: Array<{ [key: string]: string }> = [
  { es: "Mujer", ca: "Dona", en: "Female" },
  { es: "Hombre", ca: "Home", en: "Male" },
  { es: "No binario", ca: "No binari", en: "Non-binary" },
  { es: "Otros", ca: "Altres", en: "Others" },
];

export const steps = [
  { label: "Dirección", url: "/newReview/address" },
  { label: "Estancia", url: "/newReview/stay" },
  { label: "Valoración-del-piso", url: "/newReview/valuation" },
  { label: "Gestión", url: "/newReview/management" },
  { label: "Comunidad-de-vecinos", url: "/newReview/community" },
  { label: "Barrio-o-zona", url: "/newReview/neighbourhood" },
  { label: "Opinión-del-piso", url: "/newReview/opinion" },
];

export const countries: Array<{ [key: string]: string }> = [
  { ca: "Afganistan", es: "Afganistán", en: "Afghanistan" },
  { ca: "Albània", es: "Albania", en: "Albania" },
  { ca: "Algèria", es: "Argelia", en: "Algeria" },
  { ca: "Andorra", es: "Andorra", en: "Andorra" },
  { ca: "Angola", es: "Angola", en: "Angola" },
  {
    ca: "Antigua i Barbuda",
    es: "Antigua y Barbuda",
    en: "Antigua and Barbuda",
  },
  { ca: "Argentina", es: "Argentina", en: "Argentina" },
  { ca: "Armènia", es: "Armenia", en: "Armenia" },
  { ca: "Austràlia", es: "Australia", en: "Australia" },
  { ca: "Àustria", es: "Austria", en: "Austria" },
  { ca: "Azerbaidjan", es: "Azerbaiyán", en: "Azerbaijan" },
  { ca: "Bahames", es: "Bahamas", en: "Bahamas" },
  { ca: "Bangla Desh", es: "Bangladés", en: "Bangladesh" },
  { ca: "Barbados", es: "Barbados", en: "Barbados" },
  { ca: "Bielorússia", es: "Bielorrusia", en: "Belarus" },
  { ca: "Bèlgica", es: "Bélgica", en: "Belgium" },
  { ca: "Belize", es: "Belice", en: "Belize" },
  { ca: "Benín", es: "Benín", en: "Benin" },
  { ca: "Bhutan", es: "Bután", en: "Bhutan" },
  { ca: "Bolívia", es: "Bolivia", en: "Bolivia" },
  {
    ca: "Bòsnia i Hercegovina",
    es: "Bosnia y Herzegovina",
    en: "Bosnia and Herzegovina",
  },
  { ca: "Botswana", es: "Botsuana", en: "Botswana" },
  { ca: "Brasil", es: "Brasil", en: "Brazil" },
  { ca: "Brunei", es: "Brunéi", en: "Brunei" },
  { ca: "Bulgària", es: "Bulgaria", en: "Bulgaria" },
  { ca: "Burkina Faso", es: "Burkina Faso", en: "Burkina Faso" },
  { ca: "Burundi", es: "Burundi", en: "Burundi" },
  { ca: "Cambodja", es: "Camboya", en: "Cambodia" },
  { ca: "Camerun", es: "Camerún", en: "Cameroon" },
  { ca: "Canadà", es: "Canadá", en: "Canada" },
  { ca: "Cap Verd", es: "Cabo Verde", en: "Cape Verde" },
  { ca: "Txad", es: "Chad", en: "Chad" },
  { ca: "Xile", es: "Chile", en: "Chile" },
  { ca: "Xina", es: "China", en: "China" },
  { ca: "Xipre", es: "Chipre", en: "Cyprus" },
  { ca: "Colòmbia", es: "Colombia", en: "Colombia" },
  { ca: "Comores", es: "Comoras", en: "Comoros" },
  { ca: "Congo", es: "Congo", en: "Congo" },
  { ca: "Costa Rica", es: "Costa Rica", en: "Costa Rica" },
  { ca: "Costa d’Ivori", es: "Costa de Marfil", en: "Côte d'Ivoire" },
  { ca: "Croàcia", es: "Croacia", en: "Croatia" },
  { ca: "Cuba", es: "Cuba", en: "Cuba" },
  { ca: "Dinamarca", es: "Dinamarca", en: "Denmark" },
  { ca: "Djibouti", es: "Yibuti", en: "Djibouti" },
  { ca: "Dominica", es: "Dominica", en: "Dominica" },
  {
    ca: "República Dominicana",
    es: "República Dominicana",
    en: "Dominican Republic",
  },
  { ca: "Equador", es: "Ecuador", en: "Ecuador" },
  { ca: "Egipte", es: "Egipto", en: "Egypt" },
  { ca: "El Salvador", es: "El Salvador", en: "El Salvador" },
  { ca: "Guinea Equatorial", es: "Guinea Ecuatorial", en: "Equatorial Guinea" },
  { ca: "Eritrea", es: "Eritrea", en: "Eritrea" },
  { ca: "Estònia", es: "Estonia", en: "Estonia" },
  { ca: "Etiòpia", es: "Etiopía", en: "Ethiopia" },
  { ca: "Fiji", es: "Fiyi", en: "Fiji" },
  { ca: "Finlàndia", es: "Finlandia", en: "Finland" },
  { ca: "França", es: "Francia", en: "France" },
  { ca: "Gabon", es: "Gabón", en: "Gabon" },
  { ca: "Gàmbia", es: "Gambia", en: "Gambia" },
  { ca: "Geòrgia", es: "Georgia", en: "Georgia" },
  { ca: "Alemanya", es: "Alemania", en: "Germany" },
  { ca: "Ghana", es: "Ghana", en: "Ghana" },
  { ca: "Grècia", es: "Grecia", en: "Greece" },
  { ca: "Grenada", es: "Granada", en: "Grenada" },
  { ca: "Guatemala", es: "Guatemala", en: "Guatemala" },
  { ca: "Guinea", es: "Guinea", en: "Guinea" },
  { ca: "Guinea-Bissau", es: "Guinea-Bisáu", en: "Guinea-Bissau" },
  { ca: "Guyana", es: "Guyana", en: "Guyana" },
  { ca: "Haití", es: "Haití", en: "Haiti" },
  { ca: "Hondures", es: "Honduras", en: "Honduras" },
  { ca: "Hongria", es: "Hungría", en: "Hungary" },
  { ca: "Islàndia", es: "Islandia", en: "Iceland" },
  { ca: "Índia", es: "India", en: "India" },
  { ca: "Indonèsia", es: "Indonesia", en: "Indonesia" },
  { ca: "Iran", es: "Irán", en: "Iran" },
  { ca: "Iraq", es: "Iraq", en: "Iraq" },
  { ca: "Irlanda", es: "Irlanda", en: "Ireland" },
  { ca: "Israel", es: "Israel", en: "Israel" },
  { ca: "Itàlia", es: "Italia", en: "Italy" },
  { ca: "Jamaica", es: "Jamaica", en: "Jamaica" },
  { ca: "Japó", es: "Japón", en: "Japan" },
  { ca: "Jordània", es: "Jordania", en: "Jordan" },
  { ca: "Kazakhstan", es: "Kazajistán", en: "Kazakhstan" },
  { ca: "Kenya", es: "Kenia", en: "Kenya" },
  { ca: "Kiribati", es: "Kiribati", en: "Kiribati" },
  { ca: "Kosovo", es: "Kosovo", en: "Kosovo" },
  { ca: "Kuwait", es: "Kuwait", en: "Kuwait" },
  { ca: "Kirguizistan", es: "Kirguistán", en: "Kyrgyzstan" },
  { ca: "Laos", es: "Laos", en: "Laos" },
  { ca: "Letònia", es: "Letonia", en: "Latvia" },
  { ca: "Líban", es: "Líbano", en: "Lebanon" },
  { ca: "Lesotho", es: "Lesoto", en: "Lesotho" },
  { ca: "Libèria", es: "Liberia", en: "Liberia" },
  { ca: "Líbia", es: "Libia", en: "Libya" },
  { ca: "Liechtenstein", es: "Liechtenstein", en: "Liechtenstein" },
  { ca: "Lituània", es: "Lituania", en: "Lithuania" },
  { ca: "Luxemburg", es: "Luxemburgo", en: "Luxembourg" },
  {
    ca: "Macedònia del Nord",
    es: "Macedonia del Norte",
    en: "North Macedonia",
  },
  { ca: "Madagascar", es: "Madagascar", en: "Madagascar" },
  { ca: "Malawi", es: "Malawi", en: "Malawi" },
  { ca: "Malàisia", es: "Malasia", en: "Malaysia" },
  { ca: "Maldives", es: "Maldivas", en: "Maldives" },
  { ca: "Mali", es: "Mali", en: "Mali" },
  { ca: "Malta", es: "Malta", en: "Malta" },
  { ca: "Illes Marshall", es: "Islas Marshall", en: "Marshall Islands" },
  { ca: "Mauritània", es: "Mauritania", en: "Mauritania" },
  { ca: "Maurici", es: "Mauricio", en: "Mauritius" },
  { ca: "Mèxic", es: "México", en: "Mexico" },
  { ca: "Micronèsia", es: "Micronesia", en: "Micronesia" },
  { ca: "Moldàvia", es: "Moldavia", en: "Moldova" },
  { ca: "Mònaco", es: "Mónaco", en: "Monaco" },
  { ca: "Mongòlia", es: "Mongolia", en: "Mongolia" },
  { ca: "Montenegro", es: "Montenegro", en: "Montenegro" },
  { ca: "Marroc", es: "Marruecos", en: "Morocco" },
  { ca: "Moçambic", es: "Mozambique", en: "Mozambique" },
  { ca: "Myanmar", es: "Myanmar", en: "Myanmar" },
  { ca: "Namíbia", es: "Namibia", en: "Namibia" },
  { ca: "Nauru", es: "Nauru", en: "Nauru" },
  { ca: "Nepal", es: "Nepal", en: "Nepal" },
  { ca: "Països Baixos", es: "Países Bajos", en: "Netherlands" },
  { ca: "Nova Zelanda", es: "Nueva Zelanda", en: "New Zealand" },
  { ca: "Nicaragua", es: "Nicaragua", en: "Nicaragua" },
  { ca: "Níger", es: "Níger", en: "Niger" },
  { ca: "Nigèria", es: "Nigeria", en: "Nigeria" },
  { ca: "Corea del Nord", es: "Corea del Norte", en: "North Korea" },
  { ca: "Noruega", es: "Noruega", en: "Norway" },
  { ca: "Oman", es: "Omán", en: "Oman" },
  { ca: "Pakistan", es: "Pakistán", en: "Pakistan" },
  { ca: "Palau", es: "Palaos", en: "Palau" },
  { ca: "Palestina", es: "Palestina", en: "Palestine" },
  { ca: "Panamà", es: "Panamá", en: "Panama" },
  { ca: "Papua Nova Guinea", es: "Papúa Nueva Guinea", en: "Papua New Guinea" },
  { ca: "Paraguai", es: "Paraguay", en: "Paraguay" },
  { ca: "Perú", es: "Perú", en: "Peru" },
  { ca: "Filipines", es: "Filipinas", en: "Philippines" },
  { ca: "Polònia", es: "Polonia", en: "Poland" },
  { ca: "Portugal", es: "Portugal", en: "Portugal" },
  { ca: "Qatar", es: "Catar", en: "Qatar" },
  { ca: "Romania", es: "Rumania", en: "Romania" },
  { ca: "Rússia", es: "Rusia", en: "Russia" },
  { ca: "Ruanda", es: "Ruanda", en: "Rwanda" },
  {
    ca: "Saint Kitts i Nevis",
    es: "San Cristóbal y Nieves",
    en: "Saint Kitts and Nevis",
  },
  { ca: "Santa Llúcia", es: "Santa Lucía", en: "Saint Lucia" },
  {
    ca: "Saint Vincent i les Grenadines",
    es: "San Vicente y las Granadinas",
    en: "Saint Vincent and the Grenadines",
  },
  { ca: "Samoa", es: "Samoa", en: "Samoa" },
  { ca: "Saint Marino", es: "San Marino", en: "San Marino" },
  {
    ca: "Sao Tome i Principe",
    es: "Santo Tomé y Príncipe",
    en: "Sao Tome and Principe",
  },
  { ca: "Aràbia Saudita", es: "Arabia Saudita", en: "Saudi Arabia" },
  { ca: "Senegal", es: "Senegal", en: "Senegal" },
  { ca: "Sèrbia", es: "Serbia", en: "Serbia" },
  { ca: "Seychelles", es: "Seychelles", en: "Seychelles" },
  { ca: "Sierra Leone", es: "Sierra Leona", en: "Sierra Leone" },
  { ca: "Singapur", es: "Singapur", en: "Singapore" },
  { ca: "Eslovàquia", es: "Eslovaquia", en: "Slovakia" },
  { ca: "Eslovènia", es: "Eslovenia", en: "Slovenia" },
  { ca: "Illes Salomó", es: "Islas Salomón", en: "Solomon Islands" },
  { ca: "Somàlia", es: "Somalia", en: "Somalia" },
  { ca: "Sud-àfrica", es: "Sudáfrica", en: "South Africa" },
  { ca: "Corea del Sud", es: "Corea del Sur", en: "South Korea" },
  { ca: "Sudan del Sud", es: "Sudán del Sur", en: "South Sudan" },
  { ca: "Espanya", es: "España", en: "Spain" },
  { ca: "Sri Lanka", es: "Sri Lanka", en: "Sri Lanka" },
  { ca: "Sudan", es: "Sudán", en: "Sudan" },
  { ca: "Surinam", es: "Surinam", en: "Suriname" },
  { ca: "Suècia", es: "Suecia", en: "Sweden" },
  { ca: "Suïssa", es: "Suiza", en: "Switzerland" },
  { ca: "Síria", es: "Siria", en: "Syria" },
  { ca: "Taiwan", es: "Taiwán", en: "Taiwan" },
  { ca: "Tajikistan", es: "Tayikistán", en: "Tajikistan" },
  { ca: "Tanzània", es: "Tanzania", en: "Tanzania" },
  { ca: "Tailàndia", es: "Tailandia", en: "Thailand" },
  { ca: "Timor Oriental", es: "Timor Oriental", en: "Timor-Leste" },
  { ca: "Togo", es: "Togo", en: "Togo" },
  { ca: "Tonga", es: "Tonga", en: "Tonga" },
  {
    ca: "Trinitat i Tobago",
    es: "Trinidad y Tobago",
    en: "Trinidad and Tobago",
  },
  { ca: "Tunísia", es: "Túnez", en: "Tunisia" },
  { ca: "Turquia", es: "Turquía", en: "Turkey" },
  { ca: "Turkmenistan", es: "Turkmenistán", en: "Turkmenistan" },
  { ca: "Tuvalu", es: "Tuvalu", en: "Tuvalu" },
  { ca: "Uganda", es: "Uganda", en: "Uganda" },
  { ca: "Ucraïna", es: "Ucrania", en: "Ukraine" },
  {
    ca: "Emirats Àrabs Units",
    es: "Emiratos Árabes Unidos",
    en: "United Arab Emirates",
  },
  { ca: "Regne Unit", es: "Reino Unido", en: "United Kingdom" },
  {
    ca: "Estats Units d’Amèrica",
    es: "Estados Unidos de América",
    en: "United States of America",
  },
  { ca: "Uruguai", es: "Uruguay", en: "Uruguay" },
  { ca: "Uzbekistan", es: "Uzbekistán", en: "Uzbekistan" },
  { ca: "Vanuatu", es: "Vanuatu", en: "Vanuatu" },
  { ca: "Ciutat del Vaticà", es: "Ciudad del Vaticano", en: "Vatican City" },
  { ca: "Veneçuela", es: "Venezuela", en: "Venezuela" },
  { ca: "Vietnam", es: "Vietnam", en: "Vietnam" },
  { ca: "Iemen", es: "Yemen", en: "Yemen" },
  { ca: "Zàmbia", es: "Zambia", en: "Zambia" },
  { ca: "Zimbabwe", es: "Zimbabue", en: "Zimbabwe" },
];

export const reviewConfigParams = {
  buildingQuality: {
    summerTemperature: ["isolated", "good", "hot"],
    winterTemperature: ["isolated", "good", "cold"],
    noise: ["quiet", "good", "noisy", "very-noisy"],
    light: ["poor-light", "dim-light", "bright", "very-bright"],
    maintenance: ["excellent", "good", "acceptable", "poor", "very-poor"],
    services: [
      "heating",
      "air-conditioning",
      "gas",
      "terrace",
      "balcony",
      "patio",
    ],
  },
  landlord: {
    landlordTreatment: [
      "excellent",
      "good",
      "acceptable",
      "poor",
      "no-contact",
    ],
    problemSolving: ["excellent", "good", "acceptable", "slow", "slow-useless"],
    deposit: ["returned", "returned-with-deductions", "not-returned"],
  },
  neighbors: {
    buildingNeighborhood: [
      "familiar",
      "young-couples",
      "students",
      "shared",
      "seniors",
    ],
    touristicApartments: ["yes-tolerable", "yes-annoying", "no"],
    neighborsRelationship: ["excellent", "friendly", "poor", "no-relations"],
    buildingMaintenance: ["excellent", "good", "acceptable", "poor"],
    buildingCleaning: ["excellent", "good", "poor", "no-cleaning"],
    services: ["lift", "cleaning", "doorman", "parking", "storage-room"],
  },
  neighbourhood: {
    vibe: ["quiet", "festive", "familiar", "student-oriented", "nightlife"],
    tourists: ["many", "some", "few", "none"],
    noise: ["quiet", "good", "noisy"],
    security: ["excellent", "good", "acceptable", "poor"],
    cleaning: ["good", "poor", "very-poor"],
    services: [
      "supermarket",
      "schools",
      "metro",
      "bus",
      "shops",
      "market",
      "restaurants",
      "medical-center",
      "mall",
      "veterinarian",
      "gym",
      "playground",
      "pharmacy",
      "bike-parking",
      "bicing",
      "park",
      "children-area",
    ],
  },
};
